title: "Ajay Singh"
email: admin@ajaysingh.com.np
description: >-
  A basic blog site with jekyll and github pages. More description comming soon.

# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ajaysingh.com.np"
twitter_username: singh_ajaykumar
github_username:  mentormaya

# Build settings
theme: minima
plugins:
  - jekyll-feed
